version: '3.8'
services:
  db:
    image: mysql
    container_name: database
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: tasks
      MYSQL_ROOT_PASSWORD: password  # Should be done via env
    ports:
      - '3306:3306'
  rabbitmq:  # Should have non-default credentials
    image: rabbitmq
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
  app:
    image: task-manager
    ports:
      - 3000:3000
    restart: unless-stopped
    entrypoint: yarn start:docker
    depends_on:
      - db
      - rabbitmq